#!/usr/bin/env bash
# updates a server and installs Nginx
sudo apt-get update -y
sudo apt-get install nginx -y
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee "/var/www/html/index.html"
sudo service nginx restart
