#!/usr/bin/env bash
# adds 404
sudo apt-get update -y
sudo apt-get install nginx -y
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
error_str="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "36i $error_str" /etc/nginx/sites-available/default
sudo service nginx restart
