#!/usr/bin/env bash
# copies web-01 server config to web-02
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i '/server_name _;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanenet;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i '/server_name _; a error_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\troot /var/www/html;\n\tinternat;\n\t}' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/ a add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restart
