#!/usr/bin/env bash
#installs HAproxy and load balancer
sudo apt-get update
sudo apt-get -y install haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo echo -e "frontend front\n\tbind *:80\n\tmode http\n\tdefault_backend back\nbackend back\n\tbalance roundrobin\n\tserver 2392-web-01 34.73.155.83:80 check\n\tserver 2392-web-02 34.138.115.85:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
